### PR TITLE
tidb: add bank-multitable and g2 test 

### PR DESCRIPTION
**Pull request by cwen0**
In this pr 
* add bank-multitable test to test tidb
* fix some tiny bugs in tidb test

### CODE REVIEW

**Comment by siddontang** [comment]
I prefer removing G2 now because we can't support serializable isolation.

**Comment by maoling** [comment]
@siddontang  Could you plz give a help for this [issue](https://github.com/jepsen-io/jepsen/pull/58#issuecomment-478326200). very thanks：D

**Comment by siddontang** [comment]
@maoling 

I have no idea, maybe you meet some network problems? or do you run docker in Mac OS but the memory is limited?

**Comment by aphyr** [comment]
I'd say keep G2 around! It'll be a nice guidepost if you wind up aiming for serializability later. :)

**Comment by aphyr** [comment]
Thanks for these changes; you're all good to go!

**Comment by siddontang** [comment]
Hi @aphyr 

Now TiDB doesn't support serializable isolation and we don't have the plan this year too.

If we support later, we will re-add G2 :-)

**Pull request merged**
