### PR TITLE
FaunaDB: Update monotonic plot.

### PR DESCRIPTION
**Pull request by bitbckt**
This API has changed significantly, and I can't seem to figure it out in a timely manner... help? :)

### CODE REVIEW

**Comment by aphyr** [comment]
Ah! Yeah, you have two options here. For a really quick fix, you can delete the nemesis-regions code altogether. The plots won't show nemesis activity, though. For a more involved fix (which... should actually make the plot code simpler), use (perf/plot!) and related functions: for an example, see

https://github.com/jepsen-io/jepsen/blob/master/jepsen/src/jepsen/checker/clock.clj#L47-L74

The gist is that you construct a map like {:preamble [gnuplot commands ...], :series [{:title :with :data} ...]; the plot! function then takes care of things like bounds checks, rendering dummy series, nemeses, etc.

**Comment by bitbckt** [comment]
I'm not sure if this works yet - testing now - but I think it's the right idea...

**Comment by bitbckt** [comment]
Got it! :)

**Comment by aphyr** [comment]
Cool cool, thanks!

**Pull request merged**
