### PR TITLE
jepsen.os.debian: Support JDK11.

### PR DESCRIPTION
**Pull request by bitbckt**

### CODE REVIEW

**Comment by aphyr** [comment]
Are we legally allowed to do this with the changes to the Oracle JDK license agreement? IIRC there's new language about production systems and I'm not sure whether Jepsen would fall under that...

**Comment by bitbckt** [comment]
Hmm. Good point. Perhaps we want OpenJDK11 instead?

**Comment by aphyr** [comment]
I think that might be our safest option, and it'd beat having to do the Oracle installer dance. I know it's a pain, haha.

**Comment by bitbckt** [comment]
It sure is. :) I will update.

**Comment by bitbckt** [comment]
This seems to work well in my testing on a fresh cluster, but be sure Oracle hasn't already poisoned `sources.list` or you're in for a bad time...

**Comment by aphyr** [comment]
I'll take it! Thanks! :)

**Pull request merged**
