### PR TITLE
add java.xml.bind on Java 9

### PR DESCRIPTION
**Pull request by yakovzaytsev**
> lein run test --help

fails in cockroachdb with 

> java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter

I had to add java.xml.bind in cockroachdb/project.clj

### CODE REVIEW

**Comment by aphyr** [comment]
Hmmmm. I think this means the generated jars will still be broken if they're executed outside lein--what about pulling in the jaxb dependency instead?

**Comment by yakovzaytsev** [comment]
Let me look into it.

**Comment by tirkarthi** [comment]
Can you please attach the full stack trace. I suspect one the dependency is pulling the class that was removed in JDK 9 and could be fixed in the dependency.

**Comment by tirkarthi** [comment]
I haven't tested it but as per https://github.com/reagent-project/reagent-frontend-template/issues/9#issuecomment-374412204 adding a dependency of `[javax.xml.bind/jaxb-api "2.3.0"]` might resolve the issue.

**Comment by remyrd** [comment]
Same behavior on Java 11.
> adding a dependency of [javax.xml.bind/jaxb-api "2.3.0"] might resolve the issue.
It does.

**Pull request closed without merging**
