### PR TITLE
adding jecci: Jepsen and Elle based Consistency Checking Interface

### PR DESCRIPTION
**Pull request by michaelzenz**
A framework that tries to ease the burden for developers to build tests for their distributed system.

### CODE REVIEW

**Comment by aphyr** [comment]
Thank you for your hard work! This is a good deal more than I can reasonably maintain going forward--I think it's best if you publish this as a separate library.

**Comment by michaelzenz** [comment]
> Thank you for your hard work! This is a good deal more than I can reasonably maintain going forward--I think it's best if you publish this as a separate library.

OK, but can I just upload a link with some docs? Or is there any way to let more people know about my work? Do you have any advice?

**Comment by aphyr** [comment]
Happy to add a link to the README--just let me know where you wind up putting the repo. To let folks know, I'd write an email to the mailing list: https://groups.google.com/a/jepsen.io/forum/#!forum/talk.

**Comment by michaelzenz** [comment]
> Happy to add a link to the README--just let me know where you wind up putting the repo. To let folks know, I'd write an email to the mailing list: https://groups.google.com/a/jepsen.io/forum/#!forum/talk.

It's here!
https://github.com/michaelzenz/jecci

: )

**Comment by aphyr** [comment]
Right, added a link to the README. Thank!

**Pull request closed without merging**
