### PR TITLE
Allow decrements for counter checker

### PR DESCRIPTION
**Pull request by ttyusupov**
Taken `checker.counter` changes from https://github.com/riptano/jepsen/blob/master/jepsen/src/jepsen/checker.clj#L182 and updated to be compatible with Jepsen framework 0.3.3, also did some refactoring.

### CODE REVIEW

**Comment by aphyr** [comment]
It turns out that this checker doesn't pass the tests, and looking at its output, it seems... drastically wrong. I think it could emit both false positives and false negatives. I don't actually understand what's going on in the new checker algorithm--would you like to take a look before I dive in and try and figure out how it works?

**Comment by ttyusupov** [comment]
How can I run tests for this checker? 
Do you have examples of wrong behavior of the checker?

I've taken it from Cassandra Jepsen tests https://github.com/riptano/jepsen/blob/master/jepsen/src/jepsen/checker.clj#L182 and did some refactoring - https://github.com/YugaByte/jepsen/pull/14/commits . Also added comments about how it works in the code itself and there is some discussion in the PR - https://github.com/YugaByte/jepsen/pull/14/files#diff-adb08c88c67ce1b14de4490bf0ddd218R381.

**Comment by aphyr** [comment]
You can run the tests with `lein test`. As an example, in the first case in this test, the new checker incorrectly infers an upper bound of 7, rather than 15, for the first OK operation.

```
Testing jepsen.checker-test

FAIL in (counter-test) (checker_test.clj:126)
interleaved concurrent reads and writes

expected: {:errors ([0 100 7]),
           :reads [[0 6 7] [0 0 1] [0 3 3] [0 100 7] [0 15 15]],
           :valid? false}
  actual: {:errors [[0 100 15]],
           :reads [[0 6 15] [0 0 15] [0 3 15] [0 100 15] [0 15 15]],
           :valid? false}

    diff: - {:errors [[nil nil 7]],
             :reads [[nil nil 7] [nil nil 1] [nil nil 3] [nil nil 7]]}
          + {:errors [[nil nil 15]],
             :reads [[nil nil 15] [nil nil 15] [nil nil 15] [nil nil 15]]}
         
FAIL in (counter-test) (checker_test.clj:151)
rolling reads and writes

expected: {:errors ([1 5 3]), :reads [[0 0 0] [1 3 3] [1 5 3]], :valid? false}
  actual: {:errors [[1 5 3]], :reads [[0 0 1] [0 3 3] [1 5 3]], :valid? false}

    diff: - {:reads [[nil nil 0] [1]]}
          + {:reads [[nil nil 1] [0]]}
         
Ran 9 tests containing 24 assertions.
2 failures, 0 errors.
```

**Comment by ttyusupov** [comment]
Actually, this is not the first OK operation, but third, looks like test skips first read ops. I've added debug logs into checker:
```
18:25:45.960 [main] INFO  jepsen.checker - pending reads:  {}
18:25:45.965 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 0, :type :invoke, :f :read, :value 0, :index -1}
18:25:45.971 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0]]}
18:25:45.971 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 0, :type :ok, :f :read, :value 0, :index -1}
18:25:45.971 [main] INFO  jepsen.checker - value:  0
18:25:45.971 [main] INFO  jepsen.checker - read:  [0 0 0]
18:25:45.972 [main] INFO  jepsen.checker - pending reads:  {}
18:25:45.973 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 0, :type :invoke, :f :read, :value 1, :index -1}
18:25:45.973 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0]]}
18:25:45.973 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 0, :type :ok, :f :read, :value 1, :index -1}
18:25:45.973 [main] INFO  jepsen.checker - value:  1
18:25:45.973 [main] INFO  jepsen.checker - read:  [0 1 0]
18:25:45.975 [main] INFO  jepsen.checker - pending reads:  {}
18:25:45.975 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 0, :type :invoke, :f :read, :value 6, :index -1}
18:25:45.975 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0]]}
18:25:45.975 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 1, :type :invoke, :f :add, :value 1, :index -1}
18:25:45.977 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1]]}
18:25:45.977 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 2, :type :invoke, :f :read, :value 0, :index -1}
18:25:45.977 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1]], 2 [[0 1]]}
18:25:45.977 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 3, :type :invoke, :f :add, :value 2, :index -1}
18:25:45.977 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1] [0 3]], 2 [[0 1] [0 3]]}
18:25:45.977 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 4, :type :invoke, :f :read, :value 3, :index -1}
18:25:45.977 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1] [0 3]], 2 [[0 1] [0 3]], 4 [[0 3]]}
18:25:45.978 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 5, :type :invoke, :f :add, :value 4, :index -1}
18:25:45.978 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1] [0 3] [0 7]], 2 [[0 1] [0 3] [0 7]], 4 [[0 3] [0 7]]}
18:25:45.978 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 6, :type :invoke, :f :read, :value 100, :index -1}
18:25:45.978 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1] [0 3] [0 7]], 2 [[0 1] [0 3] [0 7]], 4 [[0 3] [0 7]], 6 [[0 7]]}
18:25:45.978 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 7, :type :invoke, :f :add, :value 8, :index -1}
18:25:45.978 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1] [0 3] [0 7] [0 15]], 2 [[0 1] [0 3] [0 7] [0 15]], 4 [[0 3] [0 7] [0 15]], 6 [[0 7] [0 15]]}
18:25:45.979 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 8, :type :invoke, :f :read, :value 15, :index -1}
18:25:45.979 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1] [0 3] [0 7] [0 15]], 2 [[0 1] [0 3] [0 7] [0 15]], 4 [[0 3] [0 7] [0 15]], 6 [[0 7] [0 15]], 8 [[0 15]]}
18:25:45.979 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 0, :type :ok, :f :read, :value 6, :index -1}
18:25:45.979 [main] INFO  jepsen.checker - value:  6
18:25:45.979 [main] INFO  jepsen.checker - read:  [0 6 7]
18:25:45.979 [main] INFO  jepsen.checker - pending reads:  {2 [[0 1] [0 3] [0 7] [0 15]], 4 [[0 3] [0 7] [0 15]], 6 [[0 7] [0 15]], 8 [[0 15]]}
18:25:45.979 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 1, :type :ok, :f :add, :value 1, :index -1}
18:25:45.980 [main] INFO  jepsen.checker - pending reads:  {2 [[0 1] [0 3] [0 7] [0 15] [1 15]], 4 [[0 3] [0 7] [0 15] [1 15]], 6 [[0 7] [0 15] [1 15]], 8 [[0 15] [1 15]]}
18:25:45.980 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 2, :type :ok, :f :read, :value 0, :index -1}
18:25:45.980 [main] INFO  jepsen.checker - value:  0
18:25:45.980 [main] INFO  jepsen.checker - read:  [0 0 1]
18:25:45.980 [main] INFO  jepsen.checker - pending reads:  {4 [[0 3] [0 7] [0 15] [1 15]], 6 [[0 7] [0 15] [1 15]], 8 [[0 15] [1 15]]}
18:25:45.980 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 3, :type :ok, :f :add, :value 2, :index -1}
18:25:45.981 [main] INFO  jepsen.checker - pending reads:  {4 [[0 3] [0 7] [0 15] [1 15] [3 15]], 6 [[0 7] [0 15] [1 15] [3 15]], 8 [[0 15] [1 15] [3 15]]}
18:25:45.981 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 4, :type :ok, :f :read, :value 3, :index -1}
18:25:45.981 [main] INFO  jepsen.checker - value:  3
18:25:45.981 [main] INFO  jepsen.checker - read:  [0 3 3]
18:25:45.981 [main] INFO  jepsen.checker - pending reads:  {6 [[0 7] [0 15] [1 15] [3 15]], 8 [[0 15] [1 15] [3 15]]}
18:25:45.981 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 5, :type :ok, :f :add, :value 4, :index -1}
18:25:45.981 [main] INFO  jepsen.checker - pending reads:  {6 [[0 7] [0 15] [1 15] [3 15] [7 15]], 8 [[0 15] [1 15] [3 15] [7 15]]}
18:25:45.981 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 6, :type :ok, :f :read, :value 100, :index -1}
18:25:45.981 [main] INFO  jepsen.checker - value:  100
18:25:45.982 [main] INFO  jepsen.checker - read:  [0 100 7]
18:25:45.982 [main] INFO  jepsen.checker - pending reads:  {8 [[0 15] [1 15] [3 15] [7 15]]}
18:25:45.982 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 7, :type :ok, :f :add, :value 8, :index -1}
18:25:45.982 [main] INFO  jepsen.checker - pending reads:  {8 [[0 15] [1 15] [3 15] [7 15] [15 15]]}
18:25:45.982 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 8, :type :ok, :f :read, :value 15, :index -1}
18:25:45.982 [main] INFO  jepsen.checker - value:  15
18:25:45.982 [main] INFO  jepsen.checker - read:  [0 15 15]
```

And this looks consistent with the `reads` description for checker comments:
```
             ; Map: process ID -> list of [lower upper] pairs for the pending read operation invoked by the process.
             ; Last pair in the list is most recent one and reflects the current counter possible range.
             ; List is cleared once read operation is completed.
             pending-reads      {}
             ; Completed reads: list of [lower val upper] tuples - one tuple for each successful read.
             ; Once read operation returns value val - we select first pair [lower upper] from pending-reads for which
             ; lower <= val <= upper, or just the first pair if no such pair is found (that means we've found an
             ; inconsistency, because val is out of any of possible ranges).
             ; TODO: probably we can use single union range instead of list of ranges and that will makes reads and
             ; errors reporting better.
```

**Comment by aphyr** [comment]
Hmm. Perhaps I wasn't super clear on this--the example I was talking about was the first read from this history:

```
  (testing "interleaved concurrent reads and writes"
    (is (= (check (counter) nil
                  [(invoke-op 0 :read nil)
                   (invoke-op 1 :add 1)
                   (invoke-op 2 :read nil)
                   (invoke-op 3 :add 2)
                   (invoke-op 4 :read nil)
                   (invoke-op 5 :add 4)
                   (invoke-op 6 :read nil)
                   (invoke-op 7 :add 8)
                   (invoke-op 8 :read nil)
                   (ok-op     0 :read 6)
                   (ok-op     1 :add 1)
                   (ok-op     2 :read 0)
                   (ok-op     3 :add 2)
                   (ok-op     4 :read 3)
                   (ok-op     5 :add 4)
                   (ok-op     6 :read 100)
                   (ok-op     7 :add 8)
                   (ok-op     8 :read 15)]
                  {})
           {:valid? false
            :reads  [[0 6 15] [0 0 15] [0 3 15] [0 100 15] [0 15 15]]
            :errors [[0 100 15]]})))
```

Process 0's read is the first invocation and first completion, and could have observed any state between 0 and 15. The current checker seems to think it couldn't have observed process 7's write of 8...

**Comment by ttyusupov** [comment]
I see, yes, we were talking about the same history, but I've mistakingly treated debug output of the previous history as the beginning of the one we are talking about. But other answers are still relevant.
So, the relevant piece of logs is:
```
18:25:45.975 [main] INFO  jepsen.checker - pending reads:  {}
18:25:45.975 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 0, :type :invoke, :f :read, :value 6, :index -1}
18:25:45.975 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0]]}
18:25:45.975 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 1, :type :invoke, :f :add, :value 1, :index -1}
18:25:45.977 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1]]}
18:25:45.977 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 2, :type :invoke, :f :read, :value 0, :index -1}
18:25:45.977 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1]], 2 [[0 1]]}
18:25:45.977 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 3, :type :invoke, :f :add, :value 2, :index -1}
18:25:45.977 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1] [0 3]], 2 [[0 1] [0 3]]}
18:25:45.977 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 4, :type :invoke, :f :read, :value 3, :index -1}
18:25:45.977 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1] [0 3]], 2 [[0 1] [0 3]], 4 [[0 3]]}
18:25:45.978 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 5, :type :invoke, :f :add, :value 4, :index -1}
18:25:45.978 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1] [0 3] [0 7]], 2 [[0 1] [0 3] [0 7]], 4 [[0 3] [0 7]]}
18:25:45.978 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 6, :type :invoke, :f :read, :value 100, :index -1}
18:25:45.978 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1] [0 3] [0 7]], 2 [[0 1] [0 3] [0 7]], 4 [[0 3] [0 7]], 6 [[0 7]]}
18:25:45.978 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 7, :type :invoke, :f :add, :value 8, :index -1}
18:25:45.978 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1] [0 3] [0 7] [0 15]], 2 [[0 1] [0 3] [0 7] [0 15]], 4 [[0 3] [0 7] [0 15]], 6 [[0 7] [0 15]]}
18:25:45.979 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 8, :type :invoke, :f :read, :value 15, :index -1}
18:25:45.979 [main] INFO  jepsen.checker - pending reads:  {0 [[0 0] [0 1] [0 3] [0 7] [0 15]], 2 [[0 1] [0 3] [0 7] [0 15]], 4 [[0 3] [0 7] [0 15]], 6 [[0 7] [0 15]], 8 [[0 15]]}
*vvv*
18:25:45.979 [main] INFO  jepsen.checker - op:  #knossos.op.Op{:process 0, :type :ok, :f :read, :value 6, :index -1}
18:25:45.979 [main] INFO  jepsen.checker - value:  6
18:25:45.979 [main] INFO  jepsen.checker - read:  [0 6 7]
```

Just before getting `:ok :read 6` we have following `pending reads` for process 0:
```
{0 [[0 0] [0 1] [0 3] [0 7] [0 15]]
```

So, possible ranges for the counter are `[0 0] [0 1] [0 3] [0 7] [0 15]`. Checker looks through them trying to find first range which contains the value `6` and finds `[0 7]` and return it as a valid read.

The error which checker found is `errors [[0 100 15]]` - that means read of value `100` is out of all possible ranges and the way checker work in case of error - returns first possible range which turns out to be `0 15`.

This checker reporting behavior was taken from original Cassandra counter checker, I agree we can improve the reporting, so it returns more relevant ranges instead of what is currently returns. But reporting is not affecting the actual history verification.

**Comment by ttyusupov** [comment]
I also found that it can treat some invalid histories as valid when I was porting this counter from original Cassandra Jepsen tests and looked into original checker implementation (without decrement support) and found that it also have this issue and we have discussed it with you in this ticket: https://github.com/jepsen-io/jepsen/issues/303

**Comment by ttyusupov** [comment]
But looks like if we update this checker as mentioned in https://github.com/yugabyte/jepsen/blob/master-yb/jepsen/src/jepsen/checker.clj#L695 - it will have less false positives and false negatives, because currently it doesn't reduce the list of possible value ranges on `:ok` operations.

**Comment by aphyr** [comment]
Yeah, "first possible range" is, uh, still wrong. I'm... kind of inclined to revert the whole thing, cuz this feels like not only is it incorrect, but it's also a good deal less efficient than it used to be. We filter out failed operations properly now, which should address #303.

**Comment by ttyusupov** [comment]
Right, filtering out failed operations will address #303 partly, there are still invalid cases which won't be caught even by original checker (there is one example in #303). But I understand it is probably computationally hard to avoid all false negatives.

Yes, I think it is better to use the original checker for counter incrementing tests, but this checker could still be useful for a counter test with both increments and decrements. However, it is better to update it to track the current range instead of storing a list of ranges including obsolete ones.

**Comment by aphyr** [comment]
Yeah, the other case you discussed in 303 is NP-hard, which is kinda the opposite direction I want to go for a high-throughput test like a counter. The thing is that *no* Jepsen test can guarantee it finds all problems in a history: we can only be sound, not complete. It's OK if we miss some bugs, because this checker's job is to be fast over large histories and high contention--we have different tests (like sets and linearizable registers) which cover the space more rigorously.

**Pull request merged**
