### PR TITLE
Add a flag, --logging-json, which enables JSON structured Jepsen logs.

### PR DESCRIPTION
**Pull request by stevana**

### CODE REVIEW

**Comment by aphyr** [comment]
Cool! I, uh, should note that Jepsen has a habit of printing some things to stdout as well, so this may not be toootally parseable output. You'll find machine-readable dumps of test runs in `store/latest`. :)

**Comment by stevana** [comment]
Yeah, I noticed. E.g.: https://github.com/jepsen-io/jepsen/blob/f203db2b2715a955337b4b51060599a77ba0f299/jepsen/src/jepsen/control/util.clj#L276 ruins my otherwise nicely structured db logs, :-/.

I'd like to create a unified log of all my db logs and the Jepsen log. Let's see how far I get with `grep`ing my way around the unstructured bits.

**Comment by aphyr** [comment]
If you've got an EDN or Fressian reader handy, you should be able to parse the histories directly from history.edn or test.fressian. That's not gonna include *all* logs, but it does cover operations.

**Comment by stevana** [comment]
Was hoping I could just feed everything to https://github.com/microsoft/logmerge . But thanks, I'll keep that in mind.

**Comment by aphyr** [comment]
Ah. Would you like me to revert?

**Comment by stevana** [comment]
This PR should make it easier to use that tool, so no. :-)

**Pull request merged**
