### PR TITLE
[Jepsen] Update version to 0.1.16-SNAPSHOT

### PR DESCRIPTION
**Pull request by DeCarabas**
Just a small tweak the project version to `0.1.16-SNAPSHOT`, now that `0.1.15` has been released.

I didn't update any of the specific database tests since it looks like they maybe version Jepsen individually? Let me know if you want me to update those too...

### CODE REVIEW

**Comment by aphyr** [comment]
No worries about updating individual tests. :)

**Comment by DeCarabas** [comment]
Thank you very much! May ask another small favor, for you to publish the snapshot to clojars?

**Comment by aphyr** [comment]
Sure. You know you can install these locally too, right? Run `lein install` in the `jepsen` directory. :-)

**Comment by DeCarabas** [comment]
Also, I'm sorry to be a bother, do you have a sense for when there might be an official 0.1.16? I realize that you just released a 0.1.15, and releases are time-consuming...

**Comment by DeCarabas** [comment]
Ah, yeah, I *can*, but it add so much overhead to collaboration across my other co-workers. I want them to be able to run the tests I'm writing quickly and easily, and saying "oh go clone this github project and `lein install`"... it's a whole thing. :(

**Comment by aphyr** [comment]
I usually release every few months.

**Comment by aphyr** [comment]
0.1.16-SNAPSHOT's already in Clojars--can't you have your project depend on that for now?

**Comment by DeCarabas** [comment]
I can for sure, thanks again!

The environment I'm in frowns on taking dependencies on SNAPSHOT versions, but I'll twist arms and get it to work. 

Thanks so much for your support, this is super great. Already finding and fixing bugs! 🎉

**Comment by aphyr** [comment]
Sorry! I know it's inconvenient. If you've got a private artifactory or similar, you can also package your own version locally. I just wanna give this code a chance to shake out in testing before I push it out to every other user. :)

**Pull request merged**
