### PR TITLE
cockroach: better handle restarts, new macro with-restart

### PR DESCRIPTION
**Pull request by knz**
The "restart transaction" errors can be embedded in BatchUpdateExceptions as often as PGSQLExceptions, so use java.sql.SQLException to catch both.

### CODE REVIEW

**Comment by knz** [comment]
Also this PR includes a new macro `with-restart` 
This does work (I tested it locally). I didn't push my changes to tests to use it because it hurts performance, see https://github.com/cockroachdb/cockroach/issues/5935, but it'd be nice to include it in the jepsen distribution for future reference.

**Comment by tamird** [comment]
Shouldn't this be relying on the error code rather than doing string matching?

**Comment by knz** [comment]
@tamird probably, but do you know how to reliably extract the pg error code from the SQLException?

**Comment by bdarnell** [comment]
It looks like you use [exception.getSQLState](http://postgresql.nabble.com/SQLException-getErrorCode-td2175792.html). (The postgres driver doesn't implement getErrorCode because JDBC specifies that method returns an int, but postgres error codes are alphanumeric). I think you'll have to reach into the BatchUpdateException to get the underlying PSQLException. 

LGTM

**Comment by aphyr** [comment]
Thanks @knz :)

**Pull request merged**
